"""Phase 5 — Task-type / difficulty / tool-composition + failure analysis.

Reads the Commit-3 artifacts (``artifacts/phase5/enterprise_eval_results.json``)
and the per-task GT (``data/eval/enterprise_tasks.jsonl``), and produces the
grouped, *interpretable* breakdowns required by Commit 4:

- **by task type** (all 10 canonical types) — full system vs. key baselines;
- **by difficulty** (easy/medium/hard) — does performance degrade with hard
  tasks?
- **by tool composition** (single / two / three+ / clarification) — where is
  the system actually hard?
- **failure analysis** — auto-classified real failure cases (wrong routing /
  wrong tool / RAG miss / SQL error / KG coverage / analysis error /
  unsupported claim / attribution error / conflict / latency / 429 / service),
  each recorded with task / expected / actual / stage / root cause / fix.

The Phase 2/3/4 failure modes are linked into a final Failure Taxonomy so the
cross-phase story (RAG miss -> routing miss; KG coverage -> task miss;
verification -> unsupported-claim) is explicit.

Output (gitignored, regenerated by this script)::

    python scripts/analyze_enterprise_failures.py
      -> artifacts/phase5/enterprise_grouped_analysis.json
      -> artifacts/phase5/enterprise_failure_cases.json   (>= 20 real cases)
      -> artifacts/phase5/enterprise_failure_report.md
"""

from __future__ import annotations

import json
import sys
from collections import Counter, defaultdict
from pathlib import Path
from typing import Any

_PROJECT_ROOT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(_PROJECT_ROOT))

RESULTS = _PROJECT_ROOT / "artifacts" / "phase5" / "enterprise_eval_results.json"
TASKS = _PROJECT_ROOT / "data" / "eval" / "enterprise_tasks.jsonl"
OUT_DIR = _PROJECT_ROOT / "artifacts" / "phase5"

# The systems compared in the grouped tables (full system + main baselines).
COMPARE_SYSTEMS = ("A_full", "B_no_verification", "C_static_no_verification",
                   "B4_rule_routing", "B1_llm_only")

# Failure categories (the Commit-4 taxonomy).  Each maps to a root cause and
# a suggested fix, used to build the case records.
FAILURE_CATEGORIES: dict[str, dict[str, str]] = {
    "routing_failure": {"cause": "router chose a route that does not match the task capability", "fix": "tighten the capability->route rules or the confidence gate"},
    "tool_selection_error": {"cause": "predicted tool set differs from the GT tool set", "fix": "improve tool candidate aggregation / plan validation"},
    "rag_retrieval_miss": {"cause": "the RAG tool returned no usable chunk for the query", "fix": "expand KB coverage or lower top_k / improve hybrid fusion"},
    "sql_error": {"cause": "Text-to-SQL produced no executable statement or a failing one", "fix": "strengthen the schema / dictionary / few-shot prompt context"},
    "kg_coverage": {"cause": "the KG step could not run (no template / no Neo4j)", "fix": "add the required Cypher template or provide the KG service"},
    "analysis_error": {"cause": "the analysis op produced no derived value", "fix": "feed the analysis step a populated upstream table"},
    "unsupported_claim": {"cause": "a generated claim is not backed by any evidence", "fix": "the verification layer should flag it; answer guard should block critical ones"},
    "evidence_attribution_error": {"cause": "the answer cites a source the task did not need", "fix": "constrain the answer node to the declared evidence sources"},
    "conflict_handling": {"cause": "two evidence sources disagree and the guard could not resolve it", "fix": "surface the conflict to the user instead of auto-picking"},
    "llm_429": {"cause": "the LLM endpoint rate-limited / timed out mid-task", "fix": "add backoff / retry with a bounded budget"},
    "timeout": {"cause": "a stage exceeded its wall-clock budget", "fix": "raise the stage timeout or shrink the workload"},
    "service_error": {"cause": "a backing service (Milvus/Neo4j/LLM) was unreachable", "fix": "ensure the service is running in online mode"},
    "pipeline_error": {"cause": "an unhandled exception aborted the pipeline", "fix": "add stage-level error containment"},
}


def load_tasks() -> dict[str, dict[str, Any]]:
    out: dict[str, dict[str, Any]] = {}
    with TASKS.open(encoding="utf-8") as fh:
        for line in fh:
            line = line.strip()
            if line:
                t = json.loads(line)
                out[t["id"]] = t
    return out


def _group(records: list[dict[str, Any]], key: str, tasks: dict[str, dict[str, Any]]) -> dict[str, Any]:
    """Aggregate the per-task records into a group by *key*."""
    groups: dict[str, list[dict[str, Any]]] = defaultdict(list)
    for r in records:
        val = r.get(key) if key in r else tasks.get(r["id"], {}).get(key, "unknown")
        groups[str(val)].append(r)
    out: dict[str, Any] = {}
    for name, subset in groups.items():
        m = len(subset)
        out[name] = {
            "tasks": m,
            "task_success_rate": round(sum(x["task_success"] for x in subset) / m, 4) if m else 0.0,
            "route_accuracy": round(sum(x["route_correct"] for x in subset) / m, 4) if m else 0.0,
            "tool_f1": round(sum(x["tool_f1"] or 0.0 for x in subset) / m, 4) if m else 0.0,
            "plan_exact_match": round(sum(x["plan_exact_match"] for x in subset) / m, 4) if m else 0.0,
            "answer_exact": round(sum(x["answer_exact"] for x in subset) / m, 4) if m else 0.0,
        }
    return out


def _tool_composition(records: list[dict[str, Any]], tasks: dict[str, dict[str, Any]]) -> dict[str, Any]:
    """Group by number of declared GT tools: single / two / three+ / clarification."""
    buckets: dict[str, list[dict[str, Any]]] = defaultdict(list)
    for r in records:
        n = len(tasks.get(r["id"], {}).get("expected_tools", []))
        if n == 0:
            bucket = "clarification"
        elif n == 1:
            bucket = "single_tool"
        elif n == 2:
            bucket = "two_tool"
        else:
            bucket = "three_plus_tool"
        buckets[bucket].append(r)
    out: dict[str, Any] = {}
    for name in ("clarification", "single_tool", "two_tool", "three_plus_tool"):
        subset = buckets.get(name, [])
        m = len(subset)
        out[name] = {
            "tasks": m,
            "task_success_rate": round(sum(x["task_success"] for x in subset) / m, 4) if m else 0.0,
            "route_accuracy": round(sum(x["route_correct"] for x in subset) / m, 4) if m else 0.0,
            "tool_f1": round(sum(x["tool_f1"] or 0.0 for x in subset) / m, 4) if m else 0.0,
        }
    return out


def collect_failures(records: list[dict[str, Any]], tasks: dict[str, dict[str, Any]],
                     min_cases: int = 20) -> list[dict[str, Any]]:
    """Build a real, deduped failure-case list (kept in denominator order).

    A case is a task where the full system (or any compared system) did not
    succeed.  Each records expected / actual / failing stage / root cause /
    suggested fix, so the report can be cross-referenced to the taxonomy.
    """
    cases: list[dict[str, Any]] = []
    seen_ids: set[str] = set()
    for r in records:
        if r.get("task_success"):
            continue
        tid = r["id"]
        if tid in seen_ids:
            continue
        seen_ids.add(tid)
        task = tasks.get(tid, {})
        cats = list(r.get("failure_categories") or [])
        # deterministic ordering: keep the first non-service category, else first
        primary = cats[0] if cats else "tool_selection_error"
        spec = FAILURE_CATEGORIES.get(primary, FAILURE_CATEGORIES["tool_selection_error"])
        # decide the failing stage from the per-layer signals
        stage = _failing_stage(r)
        cases.append({
            "task_id": tid,
            "task_type": r.get("task_type"),
            "difficulty": r.get("difficulty"),
            "question": task.get("question", "")[:120],
            "expected": r["expected"],
            "actual": {"route": r["predicted"]["route"], "tools": r["predicted"]["tools"],
                        "answer": r["predicted"]["answer"][:200]},
            "failure_stage": stage,
            "failure_categories": cats,
            "root_cause": spec["cause"],
            "possible_fix": spec["fix"],
        })
        if len(cases) >= max(min_cases, 40):
            break
    # pad if the full system alone had < min_cases failures (e.g. very few
    # failures): add clarification / low-F1 tasks explicitly
    if len(cases) < min_cases:
        for r in records:
            if r["id"] in seen_ids or r.get("task_success"):
                continue
            task = tasks.get(r["id"], {})
            cats = list(r.get("failure_categories") or [])
            primary = cats[0] if cats else "tool_selection_error"
            spec = FAILURE_CATEGORIES.get(primary, FAILURE_CATEGORIES["tool_selection_error"])
            cases.append({
                "task_id": r["id"], "task_type": r.get("task_type"),
                "difficulty": r.get("difficulty"),
                "question": task.get("question", "")[:120],
                "expected": r["expected"],
                "actual": {"route": r["predicted"]["route"], "tools": r["predicted"]["tools"],
                            "answer": r["predicted"]["answer"][:200]},
                "failure_stage": _failing_stage(r), "failure_categories": cats,
                "root_cause": spec["cause"], "possible_fix": spec["fix"],
            })
            seen_ids.add(r["id"])
            if len(cases) >= min_cases:
                break
    return cases


def _failing_stage(r: dict[str, Any]) -> str:
    """Pick the most informative single failing stage for the report."""
    cats = set(r.get("failure_categories") or [])
    pred_route = r["predicted"]["route"]
    exp_route = r["expected"]["route"]
    if "llm_429" in cats or "service_error" in cats or "timeout" in cats:
        return "llm / service"
    if pred_route != exp_route and pred_route not in ("", "clarification"):
        return "routing"
    if r["tool_f1"] and r["tool_f1"] < 0.5:
        return "tool selection"
    if r.get("unsupported_claims") and r["unsupported_claims"].get("n_unsupported"):
        return "verification / unsupported claim"
    if r.get("critical_unsupported_leakage"):
        return "verification / critical leakage"
    if "kg_coverage" in cats:
        return "KG coverage"
    if "sql_error" in cats:
        return "SQL"
    if "rag_retrieval_miss" in cats:
        return "RAG retrieval"
    if pred_route != exp_route:
        return "routing"
    return "answer / tool"


def _write_markdown(doc: dict[str, Any], path: Path) -> None:
    lines = ["# Phase 5 — Grouped & Failure Analysis", ""]
    lines += ["## By task type (full system A_full)", "",
              "| task_type | n | success | route | tool F1 |", "|---|---:|---:|---:|---:|"]
    tt = doc["by_task_type"]["A_full"]
    for name, d in tt.items():
        lines.append(f"| {name} | {d['tasks']} | {d['task_success_rate']:.3f} | "
                     f"{d['route_accuracy']:.3f} | {d['tool_f1']:.3f} |")
    lines += ["", "## By difficulty (A_full)", "",
              "| difficulty | n | success |", "|---|---:|---:|"]
    for d in ("easy", "medium", "hard"):
        v = doc["by_difficulty"]["A_full"].get(d)
        lines.append(f"| {d} | {v['tasks']} | {v['task_success_rate']:.3f} |" if v else f"| {d} | — | — |")
    lines += ["", "## By tool composition (A_full)", "",
              "| composition | n | success | tool F1 |", "|---|---:|---:|---:|"]
    for name in ("clarification", "single_tool", "two_tool", "three_plus_tool"):
        v = doc["by_tool_composition"]["A_full"].get(name)
        lines.append(f"| {name} | {v['tasks']} | {v['task_success_rate']:.3f} | {v['tool_f1']:.3f} |"
                     if v else f"| {name} | — | — | — |")
    lines += ["", "## Failure cases (auto-classified, kept in denominator)", ""]
    for i, c in enumerate(doc["failure_cases"], start=1):
        lines += [
            f"### case {i:02d} — {c['task_id']} ({c['task_type']} / {c['difficulty']})",
            f"- question: {c['question']}",
            f"- expected: route={c['expected']['route']} tools={c['expected']['tools']}",
            f"- actual:   route={c['actual']['route']} tools={c['actual']['tools']}",
            f"- failing stage: **{c['failure_stage']}**  categories={c['failure_categories'] or ['(no stage error — pure routing/tool miss)']}",
            f"- root cause: {c['root_cause']}",
            f"- possible fix: {c['possible_fix']}",
            "",
        ]
    path.write_text("\n".join(lines) + "\n", encoding="utf-8")


def main() -> int:
    if not RESULTS.exists():
        print(f"ERROR: {RESULTS} not found — run Commit 3 (scripts/run_enterprise_ablation.py) first")
        return 2
    rep = json.loads(RESULTS.read_text(encoding="utf-8"))
    systems = rep.get("systems", {})
    tasks = load_tasks()

    # per-system grouped analysis
    by_tt: dict[str, Any] = {}
    by_diff: dict[str, Any] = {}
    by_comp: dict[str, Any] = {}
    for name, payload in systems.items():
        records = payload.get("results", [])
        by_tt[name] = _group(records, "task_type", tasks)
        by_diff[name] = _group(records, "difficulty", tasks)
        by_comp[name] = _tool_composition(records, tasks)

    # failure cases are taken from the FULL system (A_full)
    a_records = systems.get("A_full", {}).get("results", [])
    failures = collect_failures(a_records, tasks, min_cases=20)

    doc = {
        "compared_systems": [n for n in COMPARE_SYSTEMS if n in systems],
        "by_task_type": by_tt,
        "by_difficulty": by_diff,
        "by_tool_composition": by_comp,
        "failure_cases": failures,
        "failure_category_counts": dict(Counter(
            c for a in failures for c in (a["failure_categories"] or ["tool_selection_error"]))),
        "cross_phase_taxonomy": {
            "rag_retrieval_miss -> routing_miss": "Phase 2 retrieval gap surfaces as a routing/task miss in Phase 5",
            "kg_coverage -> task_miss": "Phase 2.4 graph coverage gap surfaces as a task failure",
            "verification -> unsupported_claim": "Phase 4 guard catches claims Phase 5 would otherwise leak",
            "multi_tool_order -> answer_failure": "Phase 3 plan order errors surface as answer failures",
        },
    }
    OUT_DIR.mkdir(parents=True, exist_ok=True)
    (OUT_DIR / "enterprise_grouped_analysis.json").write_text(
        json.dumps(doc, indent=2, ensure_ascii=False, default=str), encoding="utf-8")
    (OUT_DIR / "enterprise_failure_cases.json").write_text(
        json.dumps({"failure_cases": failures,
                    "failure_category_counts": doc["failure_category_counts"]},
                   indent=2, ensure_ascii=False, default=str), encoding="utf-8")
    _write_markdown(doc, OUT_DIR / "enterprise_failure_report.md")

    print(f"[commit4] {len(failures)} failure cases; "
          f"{len(doc['failure_category_counts'])} distinct categories")
    print(f"[commit4] wrote {OUT_DIR / 'enterprise_failure_report.md'}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
